apiVersion: v1
kind: Pod
metadata:
  name: csv-to-parquet
spec:
  containers:
  - name: csv-to-parquet
    image: trevorrobertsjr/pipeline:latest
    env:
    - name: SOURCE_PATH
      value: "s3://terraform-20250223034404965000000002/nyc_reviews.csv"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_SECRET_ACCESS_KEY