name: Deploy JTC Workshop to S3 and Invalidate the CloudFront Cache

on:
  push:
    branches:
      - main  # Adjust as needed

# on:
#   workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Read repository contents

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: jtc-workshop/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: jtc-workshop

      - name: Build Docusaurus site
        run: npm run build
        working-directory: jtc-workshop

      - name: Sync build artifacts to S3
        run: aws s3 sync jtc-workshop/build s3://${{ env.S3_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront cache (optional)
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        continue-on-error: true