name: Deploy JTC Workshop to S3 and Invalidate the CloudFront Cache

# on:
#   push:
#     branches:
#       - main  # Adjust as needed

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Read repository contents

env:
  AWS_ROLE_ARN: "arn:aws:iam::318168271290:role/githubActionsRole-3f62387"  # Replace with your IAM Role ARN
  AWS_REGION: "us-east-1"  # Replace with your AWS region
  S3_BUCKET_NAME: "jtc-wanfooru-com"  # Replace with your S3 bucket name
  CLOUDFRONT_DISTRIBUTION_ID: "EXO773LTLZ9H0"  # Replace if using CloudFront
  LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}  # Replace with your Lambda function name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug OIDC Token Claims
        run: |
          echo "Fetching OIDC Token..."
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          echo $TOKEN | cut -d "." -f2 | base64 -d | jq .


      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
        working-directory: jtc-workshop

      - name: Install dependencies
        run: npm ci
        working-directory: jtc-workshop

      - name: Build Docusaurus site
        run: npm run build
        working-directory: jtc-workshop

      - name: Sync build artifacts to S3
        run: aws s3 sync jtc-workshop/build s3://${{ env.S3_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront cache (optional)
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        continue-on-error: true

      # - name: Invoke Lambda function
      #   run: aws lambda invoke --function-name ${{ env.LAMBDA_FUNCTION_NAME }} /dev/null
